### ISSUE TITLE
Why do you align GNN with a transformer training from scratch instead of LLaMA?

### ISSUE THREAD

**Issue by yzhHoward** [HKUDS/GraphGPT#22]
Your work is very impressive. Aligning GNN with LM can help it fit with LLaMA. But I wonder why align with a transformer training from scratch? Is this better than align with LLaMA?

**Comment by tjb-tech** [comment]
> Your work is very impressive. Aligning GNN with LM can help it fit with LLaMA. But I wonder why align with a transformer training from scratch? Is this better than align with LLaMA?

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
Your question is great! The reason why we align GNNs with a transformer training from scratch at early text-grounding stage is that aligning GNN with a transformer is more scalable, which means more effient. We can use more text-graph data to let GNN obtain the initial semantic capabilities. Hope that my answer is helpful for you! 
Wishing you an early Merry Christmas!

**Comment by yzhHoward** [comment]
Thanks! It address my concern.
