### ISSUE TITLE
Can the GraphGPT be used for LLM inference on other domain graph without retrainng?

### ISSUE THREAD

**Issue by lushunn** [HKUDS/GraphGPT#25]
It's a wonderful research, but I have a question: all the training data seems to be collected from the research paper domain. Therefore, if it lacks the capability to zero-shot infer graphs from other domains, such as medicine or communication ?

**Comment by tjb-tech** [comment]
> It's a wonderful research, but I have a question: all the training data seems to be collected from the research paper domain. Therefore, if it lacks the capability to zero-shot infer graphs from other domains, such as medicine or communication ?

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
Your question is great! I think there are two ways to find out the answer: 
1. You can directly run GraphGPT using your domain-specific data and evalute it. 
2. If the results in your domain-specific data are not that good. I recommend you to tune GraphGPT in your data. 

And we believe that the zero-shot ability of GraphGPT in other domain graphs is still good. 
Hope my answer is help for you. Wishing you an early Merry Christmas!
